/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade004.vew;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author a1591
 */
public class AdicionarVetor extends javax.swing.JFrame {

    int vetor[] = new int[6];
    DefaultListModel lista = new DefaultListModel();
    int selecionado = 0;
       
    
    
    /**
     * Creates new form AdicionarVetor
     */
    public AdicionarVetor() {
        initComponents();
        for(int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinnerEscolherNumero = new javax.swing.JSpinner();
        buttonAdicionar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        buttonOrdenar = new javax.swing.JButton();
        lableVetor = new javax.swing.JLabel();
        lableNumeroVetor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistExibirResposta = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonAdicionar.setText("Adicionar");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        buttonOrdenar.setText("Ordenar");
        buttonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdenarActionPerformed(evt);
            }
        });

        lableVetor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableVetor.setText("vetor");

        lableNumeroVetor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableNumeroVetor.setText("[0]");

        jlistExibirResposta.setModel(lista);
        jlistExibirResposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistExibirRespostaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlistExibirResposta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(spinnerEscolherNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonOrdenar)
                            .addComponent(buttonRemover)
                            .addComponent(buttonAdicionar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(lableVetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lableNumeroVetor)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableVetor)
                    .addComponent(lableNumeroVetor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerEscolherNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAdicionar))
                        .addGap(18, 18, 18)
                        .addComponent(buttonRemover)
                        .addGap(18, 18, 18)
                        .addComponent(buttonOrdenar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        // TODO add your handling code here:
        vetor[selecionado] = Integer.parseInt(spinnerEscolherNumero.getValue().toString());
        lista.removeAllElements();
        for(int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void jlistExibirRespostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistExibirRespostaMouseClicked
        // TODO add your handling code here:
        selecionado = jlistExibirResposta.getSelectedIndex();
        lableNumeroVetor.setText("[" + selecionado + "]");
    }//GEN-LAST:event_jlistExibirRespostaMouseClicked

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        // TODO add your handling code here:
        vetor[selecionado] = 0;
        lista.removeAllElements();
        for(int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private void buttonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdenarActionPerformed
        // TODO add your handling code here:
        Arrays.sort(vetor);
        lista.removeAllElements();
        for(int i = 0; i < vetor.length; i++){
            lista.addElement(vetor[i]);
        }
    }//GEN-LAST:event_buttonOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarVetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonOrdenar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistExibirResposta;
    private javax.swing.JLabel lableNumeroVetor;
    private javax.swing.JLabel lableVetor;
    private javax.swing.JSpinner spinnerEscolherNumero;
    // End of variables declaration//GEN-END:variables
}
