/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

import java.awt.HeadlessException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author a1591
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form Views
     */
    public View() {
        initComponents();
        this.setLocationRelativeTo(null); // Centraliza a janela.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnoNascimento = new javax.swing.JLabel();
        jSpinnerAnoNascimento = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lblImgUser = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblimagemUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAnoNascimento.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblAnoNascimento.setText("Ano de Nascimento");

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon("C:\\Users\\a1591\\Documents\\NetBeansProjects\\prg03luanalves\\prg03luanalves\\src\\main\\java\\br\\com\\ifba\\atividade03\\images\\imgCalculadora.png")); // NOI18N
        btnCalcular.setText("    Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblIdade.setText("0");

        lblimagemUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\a1591\\Documents\\NetBeansProjects\\prg03luanalves\\prg03luanalves\\src\\main\\java\\br\\com\\ifba\\atividade03\\images\\imgUser.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnCalcular)
                        .addGap(73, 73, 73)
                        .addComponent(lblIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblAnoNascimento)
                        .addGap(27, 27, 27)
                        .addComponent(jSpinnerAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblImgUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblimagemUser)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAnoNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinnerAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCalcular)
                                    .addComponent(lblIdade))
                                .addGap(100, 100, 100))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblimagemUser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:    
        
        try { // Trata possivel exeção de idade futura.
            
            Integer anoNascimento = (int) jSpinnerAnoNascimento.getValue();// Pega o valor do Spinner, e converte pra inteiro, atribuindo a ele.
            Integer anoAtual = LocalDate.now().getYear(); // Pega o ano atual da seua maquina

            if (anoNascimento > anoAtual) { // Verifica se o ano de Nascimento é menor que o ano atual
                // Ano de nascimento no futuro
                JOptionPane.showMessageDialog(this, "Ano de nascimento inválido!", "Erro", JOptionPane.ERROR_MESSAGE);// Abre uma simples tela de erro, falando que a data é invalida
            } else { // Se não ele atribui a idade da subtração e converte para string, exbindo para o lbl de Idade.
                Integer idade = anoAtual - anoNascimento;
                lblIdade.setText(String.valueOf(idade));
            }

        } catch (HeadlessException e) { // Aqui captura a possivel exeção de erro ao calcular a idade, abrindo a telinha de erro.
            JOptionPane.showMessageDialog(this, "Erro ao calcular a idade: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JSpinner jSpinnerAnoNascimento;
    private javax.swing.JLabel lblAnoNascimento;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblImgUser;
    private javax.swing.JLabel lblimagemUser;
    // End of variables declaration//GEN-END:variables
}
