/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

/**
 *
 * @author a1591
 */
public class CursoAdicionar extends javax.swing.JFrame {

    /**
     * Creates new form CursoAdicionar
     */
    public CursoAdicionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teste = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JLabel();
        textFildNome = new javax.swing.JTextField();
        nomeCurso = new javax.swing.JLabel();
        textFildCurso = new javax.swing.JTextField();
        atividadeAluno = new javax.swing.JLabel();
        checkBoxAtividade = new javax.swing.JCheckBox();
        iDAluno = new javax.swing.JLabel();
        textFildiD = new javax.swing.JTextField();
        enviarAdicaoDeCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teste.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        nomeAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeAluno.setText("Digite o Nome : ");

        textFildNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFildNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFildNomeActionPerformed(evt);
            }
        });

        nomeCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeCurso.setText("Digite o Curso : ");

        textFildCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFildCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFildCursoActionPerformed(evt);
            }
        });

        atividadeAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atividadeAluno.setText("Ativo/Desativo : ");

        checkBoxAtividade.setText("Atividade");
        checkBoxAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAtividadeActionPerformed(evt);
            }
        });

        iDAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iDAluno.setText("Digite o ID :");

        textFildiD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFildiD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFildiDActionPerformed(evt);
            }
        });

        enviarAdicaoDeCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enviarAdicaoDeCurso.setText("Enviar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(enviarAdicaoDeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomeCurso)
                                            .addComponent(nomeAluno))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFildNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textFildCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(atividadeAluno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkBoxAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)
                                .addComponent(teste))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iDAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFildiD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(teste))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeAluno)
                            .addComponent(textFildNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeCurso)
                            .addComponent(textFildCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iDAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFildiD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atividadeAluno)
                    .addComponent(checkBoxAtividade))
                .addGap(33, 33, 33)
                .addComponent(enviarAdicaoDeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFildNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFildNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFildNomeActionPerformed

    private void textFildCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFildCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFildCursoActionPerformed

    private void checkBoxAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAtividadeActionPerformed

    private void textFildiDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFildiDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFildiDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoAdicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atividadeAluno;
    private javax.swing.JCheckBox checkBoxAtividade;
    private javax.swing.JButton enviarAdicaoDeCurso;
    private javax.swing.JLabel iDAluno;
    private javax.swing.JLabel nomeAluno;
    private javax.swing.JLabel nomeCurso;
    private javax.swing.JLabel teste;
    private javax.swing.JTextField textFildCurso;
    private javax.swing.JTextField textFildNome;
    private javax.swing.JTextField textFildiD;
    // End of variables declaration//GEN-END:variables
}
