/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.model.dao.CursoDAO;
import javax.swing.JFrame;

/**
 *
 * @author a1591
 */
public class CursoEditar extends javax.swing.JFrame {

    /**
     * Creates new form CursoEditar
     */
    public CursoEditar() {
        initComponents();
    }
    
    private CursoListar listarFrame; // Referência para o frame de listagem
    
    public CursoEditar(CursoListar listarFrame) {
        initComponents(); // Inicializa os componentes da interface gráfica

        this.listarFrame = listarFrame; // Recebe o frame responsável pela listagem
        
        // Adiciona um listener para detectar o fechamento da janela
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (listarFrame != null) {
                    listarFrame.readJTable(); // Atualiza a tabela no frame de listagem
                }
            }
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fecha esta janela sem encerrar o programa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeAlunoAtualizar = new javax.swing.JLabel();
        textFildNomeAtualizar = new javax.swing.JTextField();
        nomeCursoAtualizar = new javax.swing.JLabel();
        textFildCursoAtualiar = new javax.swing.JTextField();
        atividadeAlunoAtualizar = new javax.swing.JLabel();
        checkBoxAtividadeAtualizar = new javax.swing.JCheckBox();
        jLableStausAtualizacao = new javax.swing.JLabel();
        lableNumeroID = new javax.swing.JLabel();
        textFildID = new javax.swing.JTextField();
        jButtonAtualizarCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeAlunoAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeAlunoAtualizar.setText("Novo Nome : ");

        textFildNomeAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFildNomeAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFildNomeAtualizarActionPerformed(evt);
            }
        });

        nomeCursoAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeCursoAtualizar.setText("Nova Abreviação:");

        textFildCursoAtualiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFildCursoAtualiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFildCursoAtualiarActionPerformed(evt);
            }
        });

        atividadeAlunoAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atividadeAlunoAtualizar.setText("Novo Status");

        checkBoxAtividadeAtualizar.setText("Atividade");
        checkBoxAtividadeAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAtividadeAtualizarActionPerformed(evt);
            }
        });

        jLableStausAtualizacao.setText("Status");

        lableNumeroID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lableNumeroID.setText("Informe o ID para Atualizar:");

        textFildID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFildID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFildIDActionPerformed(evt);
            }
        });

        jButtonAtualizarCurso.setText("Atualizar");
        jButtonAtualizarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeCursoAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFildCursoAtualiar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(atividadeAlunoAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkBoxAtividadeAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lableNumeroID)
                                .addGap(18, 18, 18)
                                .addComponent(textFildID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nomeAlunoAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFildNomeAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAtualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLableStausAtualizacao)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableNumeroID)
                    .addComponent(textFildID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeAlunoAtualizar)
                    .addComponent(textFildNomeAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCursoAtualizar)
                    .addComponent(textFildCursoAtualiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atividadeAlunoAtualizar)
                    .addComponent(checkBoxAtividadeAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLableStausAtualizacao)
                    .addComponent(jButtonAtualizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFildNomeAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFildNomeAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFildNomeAtualizarActionPerformed

    private void textFildCursoAtualiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFildCursoAtualiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFildCursoAtualiarActionPerformed

    private void checkBoxAtividadeAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAtividadeAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAtividadeAtualizarActionPerformed

    private void textFildIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFildIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFildIDActionPerformed

    private void jButtonAtualizarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarCursoActionPerformed
        // TODO add your handling code here:
        
        // Instancia um objeto de Curso e CursoDAO
        Curso curso = new Curso();
        CursoDAO categoriaDAO = new CursoDAO();
        
        // Obtém o ID digitado no campo de texto e converte para Long
        //String numId = textFildID.getText();
        //Long numeroID = Long.parseLong(numId);
        // Logo a baixo tem outra forma de se fazer a mesma coisa

        // Busca o curso no banco de dados pelo ID
        curso = categoriaDAO.find(Long.parseLong(textFildID.getText()));

        // Atualiza os atributos do curso com os novos valores
        curso.setNome(textFildNomeAtualizar.getText()); // Atualiza o nome do curso
        curso.setCodigoCurso(textFildCursoAtualiar.getText()); // Atualiza a abreviação do curso
        curso.setAtivo(checkBoxAtividadeAtualizar.isSelected()); // Atualiza o estado de atividade do curso

        // Salva as alterações no banco de dados
        categoriaDAO.update(curso);
    }//GEN-LAST:event_jButtonAtualizarCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CursoListar listarFrame = new CursoListar();
                new CursoEditar(listarFrame).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atividadeAlunoAtualizar;
    private javax.swing.JCheckBox checkBoxAtividadeAtualizar;
    private javax.swing.JButton jButtonAtualizarCurso;
    private javax.swing.JLabel jLableStausAtualizacao;
    private javax.swing.JLabel lableNumeroID;
    private javax.swing.JLabel nomeAlunoAtualizar;
    private javax.swing.JLabel nomeCursoAtualizar;
    private javax.swing.JTextField textFildCursoAtualiar;
    private javax.swing.JTextField textFildID;
    private javax.swing.JTextField textFildNomeAtualizar;
    // End of variables declaration//GEN-END:variables
}
