/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.model.dao.CursoDAO;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author a1591
 */
public class CursoAdicionar extends javax.swing.JFrame {
    
    /**
     * Creates new form CursoAdicionar
     */
    public CursoAdicionar() {
        initComponents();
    }
  
    private CursoListar listarFrame; // Referência para o frame de listagem

    public CursoAdicionar(CursoListar listarFrame) {
        initComponents(); // Inicializa os componentes da interface gráfica

        this.listarFrame = listarFrame; // Recebe o frame responsável pela listagem
        
        // Adiciona um listener para detectar o fechamento da janela
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (listarFrame != null) {
                    listarFrame.readJTable(); // Atualiza a tabela no frame de listagem
                }
            }
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fecha esta janela sem encerrar o programa
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teste = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JLabel();
        textFildNome = new javax.swing.JTextField();
        nomeCurso = new javax.swing.JLabel();
        textFildCurso = new javax.swing.JTextField();
        atividadeAluno = new javax.swing.JLabel();
        checkBoxAtividade = new javax.swing.JCheckBox();
        enviarAdicaoDeCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teste.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        nomeAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeAluno.setText("Digite o Nome : ");

        textFildNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFildNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFildNomeActionPerformed(evt);
            }
        });

        nomeCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeCurso.setText("Abreviação Nome:");

        textFildCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFildCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFildCursoActionPerformed(evt);
            }
        });

        atividadeAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atividadeAluno.setText("Ativo/Desativo : ");

        checkBoxAtividade.setText("Atividade");
        checkBoxAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAtividadeActionPerformed(evt);
            }
        });

        enviarAdicaoDeCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enviarAdicaoDeCurso.setText("Enviar");
        enviarAdicaoDeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAdicaoDeCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(enviarAdicaoDeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCurso)
                                    .addComponent(nomeAluno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFildNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFildCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(atividadeAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addComponent(teste)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(teste))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeAluno)
                            .addComponent(textFildNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeCurso)
                            .addComponent(textFildCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atividadeAluno)
                    .addComponent(checkBoxAtividade))
                .addGap(33, 33, 33)
                .addComponent(enviarAdicaoDeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void textFildNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFildNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFildNomeActionPerformed

    private void textFildCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFildCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFildCursoActionPerformed

    private void checkBoxAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAtividadeActionPerformed

    private void enviarAdicaoDeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarAdicaoDeCursoActionPerformed
        // TODO add your handling code here:
        
        // Cria um novo objeto do tipo Curso
        Curso curso = new Curso();
        
        // Define os atributos do curso com os valores obtidos
        curso.setNome(textFildNome.getText()); // Define o nome do curso
        curso.setCodigoCurso(textFildCurso.getText()); // Define a abreviação do curso
        curso.setAtivo(checkBoxAtividade.isSelected()); // Define o estado de atividade do curso

        // Cria uma instância de CursoDAO para interagir com o banco de dados
        CursoDAO dao = new CursoDAO();
        
        // Salva o curso no banco de dados
        dao.save(curso);  

    }//GEN-LAST:event_enviarAdicaoDeCursoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CursoListar listarFrame = new CursoListar();
                new CursoAdicionar(listarFrame).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atividadeAluno;
    private javax.swing.JCheckBox checkBoxAtividade;
    private javax.swing.JButton enviarAdicaoDeCurso;
    private javax.swing.JLabel nomeAluno;
    private javax.swing.JLabel nomeCurso;
    private javax.swing.JLabel teste;
    private javax.swing.JTextField textFildCurso;
    private javax.swing.JTextField textFildNome;
    // End of variables declaration//GEN-END:variables
}
