/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09.view;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author a1591
 */
public class TelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form Pagamento
     */
    public TelaPagamento() {
        initComponents();
        this.setLocationRelativeTo(null); // Centraliza a janela.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSolicitaTipoPagamento = new javax.swing.JComboBox<>();
        lblGeradordeRecibos = new javax.swing.JLabel();
        lblFormaPagamentos = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneExibirRecibo = new javax.swing.JTextPane();
        jButtonGerarRecibo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbSolicitaTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pix", "Cartão", "Dinheiro" }));
        cbSolicitaTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSolicitaTipoPagamentoActionPerformed(evt);
            }
        });

        lblGeradordeRecibos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGeradordeRecibos.setText("Gerador de Recibos");

        lblFormaPagamentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFormaPagamentos.setText("Forma de Pagamento");

        lblValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValor.setText("Valor:");

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPaneExibirRecibo);

        jButtonGerarRecibo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonGerarRecibo.setText("Gerar Recibo");
        jButtonGerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarReciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFormaPagamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSolicitaTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButtonGerarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(lblGeradordeRecibos)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblGeradordeRecibos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPagamentos)
                    .addComponent(cbSolicitaTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButtonGerarRecibo)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSolicitaTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSolicitaTipoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSolicitaTipoPagamentoActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jButtonGerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarReciboActionPerformed
        // TODO add your handling code here:
        
        
        // Obtém a forma de pagamento selecionada no ComboBox
        String formaPagamentoSelecionada = (String) cbSolicitaTipoPagamento.getSelectedItem();

        // Obtém o valor digitado pelo usuário no campo de texto
        String valorDigitado = jTextFieldValor.getText();

        // Verifica se o campo de valor está vazio
        if (valorDigitado.isEmpty()) {
            // Exibe uma mensagem de erro se o campo estiver vazio
            JOptionPane.showMessageDialog(this, "Por favor, digite um valor.", "Erro", JOptionPane.ERROR_MESSAGE);
            return; // Interrompe a execução do método
        }

        try {
            // Converte o valor digitado para um número do tipo double
            double valor = Double.parseDouble(valorDigitado);

            // Declara uma variável para a interface de pagamento
            IPagamento ipagamento = null;

            // Verifica qual foi a forma de pagamento selecionada e instancia a classe correspondente
            switch (formaPagamentoSelecionada) {
                case "Cartão":
                    ipagamento = new PagamentoCartao(valor); // Pagamento com cartão
                    break;
                case "Pix":
                    ipagamento = new PagamentoPix(valor); // Pagamento via Pix
                    break;
                case "Dinheiro":
                    ipagamento = new PagamentoDinheiro(valor); // Pagamento em dinheiro
                    break;
                default:
                    // Caso a forma de pagamento seja inválida, exibe um erro
                    JOptionPane.showMessageDialog(this, "Forma de pagamento inválida.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return; // Interrompe a execução do método
            }

            // Se uma instância válida de pagamento foi criada
            if (ipagamento != null) {

                // Gera o recibo usando o método da interface
                String recibo = ipagamento.gerarRecibo();

                // Exibe o recibo no componente de texto (JTextPane)
                jTextPaneExibirRecibo.setText(recibo);

                // Limpa o campo de valor e reseta o ComboBox
                jTextFieldValor.setText("");
                cbSolicitaTipoPagamento.setSelectedIndex(0);

                // Chama o método para "imprimir" o recibo (pode ser uma simulação de impressão)
                ipagamento.imprimirRecibo();
            }

        } catch (NumberFormatException e) {
            // Caso o valor digitado não seja um número válido, exibe uma mensagem de erro
            JOptionPane.showMessageDialog(this, "Valor digitado inválido. Digite um número.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonGerarReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSolicitaTipoPagamento;
    private javax.swing.JButton jButtonGerarRecibo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextPane jTextPaneExibirRecibo;
    private javax.swing.JLabel lblFormaPagamentos;
    private javax.swing.JLabel lblGeradordeRecibos;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
