/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade001.view;

/**
 *
 * @author Luan Alves
 * 
 */

public class View extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public View() {
        initComponents();
        idadeResult.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeAno = new javax.swing.JLabel();
        dataNascimento = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        nameIdade = new javax.swing.JLabel();
        idadeResult = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fotoUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeAno.setText("Ano de Nascimento");
        getContentPane().add(nomeAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 62, -1, -1));
        getContentPane().add(dataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 65, 73, 25));

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon("C:\\Users\\a1591\\Documents\\NetBeansProjects\\prg03luanalves\\src\\main\\java\\br\\com\\ifba\\atividade001\\images\\download.png")); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 60));

        nameIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameIdade.setText("Idade:");
        getContentPane().add(nameIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 233, -1, -1));

        idadeResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idadeResult.setText("0");
        getContentPane().add(idadeResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 233, 92, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 139, -1, -1));

        fotoUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\a1591\\Documents\\NetBeansProjects\\prg03luanalves\\src\\main\\java\\br\\com\\ifba\\atividade001\\images\\images.jpg")); // NOI18N
        getContentPane().add(fotoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 108, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        
        // Pegando a data de nascimento e armazenando ela 
        int nascimento = Integer.parseInt(dataNascimento.getValue().toString());
        int ano = 2024;
        // Fazendo a subtração para resultar a idade
        int idade = ano - nascimento;
        // Exibindo o resultado
        idadeResult.setText("<html> " + idade);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JSpinner dataNascimento;
    private javax.swing.JLabel fotoUser;
    private javax.swing.JLabel idadeResult;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nameIdade;
    private javax.swing.JLabel nomeAno;
    // End of variables declaration//GEN-END:variables
}
